"""add status and extracted_text to documents

Revision ID: cb998362293a
Revises: a96cdaa0cbc2
Create Date: 2026-08-06 12:09:42.559901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb998362293a'
down_revision: Union[str, Sequence[str], None] = 'a96cdaa0cbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type in PostgreSQL before using it
    document_status = sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentstatus')
    document_status.create(op.get_bind(), checkfirst=True)

    op.add_column('documents', sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentstatus'), server_default='UPLOADED', nullable=False))
    op.add_column('documents', sa.Column('extracted_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'status')

    # Drop the Enum type when downgrading
    document_status = sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentstatus')
    document_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
